name: linkedin_auth
description: Flutter auth for LinkedIn using V2 APIs and OAuth 2.0, pure dart implementation.
version: 0.0.3
authors:
  - Ishaan Bahal <ishaanbahal@gmail.com>

homepage: https://github.com/ishaanbahal/LinkedIn-Auth-Flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.9+1
  uuid: ^2.0.2
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

