name: linkedin_auth
description: Flutter auth for LinkedIn using V2 APIs and OAuth 2.0, pure dart implementation.
version: 0.0.6
authors:
  - Ishaan Bahal <ishaanbahal@gmail.com>

homepage: https://github.com/ishaanbahal/LinkedIn-Auth-Flutter

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.0
  uuid: ^3.0.5
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

